### ISSUE TITLE
[BUG] Encryption doesn't match when encrypting azure connection strings

### ISSUE THREAD

**Issue by mpigram** [glasswall-sre/victoria#44]
**Describe the bug**
When trying to encrypt a connection string, you have to manually add extra semi colons to ensure the encryption matches. See connection string example below:

```
Original Connection String:
DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxxx;EndpointSuffix=xxx

Modified to enable correct encryption:
DefaultEndpointsProtocol=https;;AccountName=xxx;;AccountKey=xxxx;;EndpointSuffix=xxx
```

I looked into what could be the issue and it seems we may need to look at using a Shared Access Signature instead of a connection string. This would stop the use of the semi colons within the connection strings but still leave the issue behind of the semi colons not being properly encrypted unless they are doubled up.

Another option is we look at url encoding the connection strings before they are encrypted - see below:

[Python URL Encoding](https://www.urlencoder.io/python/#:~:text=URL%20Encoding%20query%20strings%20or,uses%20UTF%2D8%20encoding%20scheme.)

I didn't get much further than this regarding this issue but feel free to speak to me about any other queries.

**Comment by AshKapow** [comment]
@mukulgupta2138 @chrisdiao this is OK now and tested, working.
