### ISSUE TITLE
Victoria Config Command

### ISSUE THREAD

**Issue by JMoulderGW** [glasswall-sre/victoria#45]
Hi,

Could we add the command for `Victoria Config Show` to have the same output as the current `Victoria Config View` please?

This is a very low level feature request

Thanks,
Josh

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria/pull/52

**Comment by mukulgupta2138** [comment]
![image](https://user-images.githubusercontent.com/77505708/123115184-88606d80-d45d-11eb-8294-8239fc6b46c7.png)
