### ISSUE TITLE
[BUG] cryptography error when installing azure-cli-core

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria#46]
**Describe the bug**
When installing Victoria v1.0.1 there is an error about cryptography during install

**To Reproduce**
1. `pip3 install victoria`

**Expected behavior**
No errors during installation

**CLI output**
`ERROR: azure-cli-core 2.24.2 has requirement cryptography<3.4,>=3.2, but you'll have cryptography 3.4.7 which is incompatible.`

**Platform:**
 - OS: Ubuntu Docker Image (latest)
 - Shell: Bash
 - Victoria version: v1.0.1
 - Python version: 3.8.5

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria/pull/48
