### ISSUE TITLE
[REQUEST] Enhanced Error Handling Around Azure Storage

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria#50]
**Is your feature request related to a problem? Please describe.**
Adding enhanced logging to give more verbose output when Victoria is unable to connect to Azure Storage

**Comment by mukulgupta2138** [comment]
Created a PR for this https://github.com/glasswall-sre/victoria/pull/51

**Comment by mukulgupta2138** [comment]
This is now fixed
